### PR TITLE
fix: ignore redis connections error on rate limit

### LINKED ISSUE #802: fix: silently fail on rate-limit unavailability

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

On redis connection issues, rate-limit middleware is blocking the whole request workflow, and not letting through any requests.

## 💊 Fixes / Solution

Fix #802 

On redis connection issues, rate-limit middleware should be ignored, and all requests should bypass the middleware.

## 🚧 Changes

- Bypass rate-limit middleware when redis is not ready
- Update `rate-limit-redis` package to 3.1.0, to support redis reconnection, else will throw https://github.com/express-rate-limit/rate-limit-redis/issues/144

## 🛠️ Tests

- Start your redis server
- yarn dev
- Send some requests to localhost:3000
- It should returns headers like `Ratelimit-Limit`
- Stop the redis server
- It should start logging connections error on the `yarn dev` console
- Send some requests to localhost:3000
- It should return results as usual
- The headers `Ratelimit-Limit` should be missing from the headers
- Start redis again
- Send some requests to localhost:3000
- Headers `Ratelimit-Limit` should be back

### CODE REVIEW

File: src/helpers/rateLimit.ts [hunk 1]
```diff
@@ -29,6 +29,10 @@ export default rateLimit({
   standardHeaders: true,
   legacyHeaders: false,
   skip: (req, res) => {
+    if (client && !client.isReady) {
+      return true;
+    }
```
Comment (ChaituVR) [inline src/helpers/rateLimit.ts:34]:
```suggestion
    if (!client?.isReady) return true;
```

**Review by ChaituVR — APPROVED** [review]
tAck
